config/routes.rb
Songz::Application.routes.draw do

  root :to => 'home#index'
  resources :albums
  resources :songs
  resources :artists
  resources :libraries

end

app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ActiveRecord::Base
  attr_accessible :name, :photo, :photo_cache, :remote_photo_url

  has_and_belongs_to_many :songs
  mount_uploader :photo, AlbumPicUploader
  validates :name, :presence => true
end

app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :photo, :photo_cache, :remote_photo_url

  has_and_belongs_to_many :songs
  mount_uploader :photo, AlbumPicUploader
  validates :name, :presence => true
end

app/models/genre.rb
# == Schema Information
#
# Table name: genres
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Genre < ActiveRecord::Base
  attr_accessible :name

  has_and_belongs_to_many :songs
  validates :name, :presence => true
end

app/models/song.rb
# == Schema Information
#
# Table name: songs
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  photo      :string(255)
#  audio      :string(255)
#  youtube    :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Song < ActiveRecord::Base
  attr_accessible :audio, :name, :photo, :audio, :youtube, :photo_cache, :remote_photo_url

  has_and_belongs_to_many :albums
  has_and_belongs_to_many :artists
  has_and_belongs_to_many :genres

	mount_uploader :photo, SongPicUploader
  

  validates :name, :presence => true
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  def index
    @albums = Album.all
  end

  def show
    @album = Album.find(params[:id])
  end

  def new
    @album = Album.new
  end

  def edit
    @album = Album.find(params[:id])
  end

  def create
    @album = Album.new(params[:album])
	    if @album.save
	        redirect_to albums_path
		else
			render :new
		end
	end

	def update
		@album = Album.find(params[:id])
		@album.song_ids = params[:@album][:song_ids]

		if @album.update_attributes(params[:album])
			redirect_to @album
		else
			render :edit
		end
	end

	def destroy
		album = Album.find(params[:id])
		album.delete
		redirect_to albums_path
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

  def index
    @artists = Artist.all
  end

  def new
    @artist = Artist.new
  end

  def show
    @artist = Artist.find(params[:id])
  end

  def edit
    @artist = Artist.find(params[:id])
  end

  def update
    @artist = Artist.find(params[:id])
    @artist.song_ids = params[:@artist][:song_ids]
    if @artist.update_attributes(params[:artist])
      redirect_to artists_path
    else
      render :edit
    end  
  end

  def create
    @artist = Artist.new(params[:artist]) 
    if @artist.save
      redirect_to artists_path
    else
      render :new
    end
  end


  def destroy
    artist = Artist.find(params[:id])
    artist.delete
    redirect_to artists_path
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController

  def index 
    @albums = Album.all
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end

  def new
    @song = Song.new
  end

  def show
    @song = Song.find(params[:id])
  end

  def create
    @song = Song.new(params[:song])    
    if @song.save
        redirect_to songs_path
    else
      render :new
    end
  end

  def destroy
    song = Song.find(params[:id])
    song.delete
    redirect_to songs_path
  end

  def edit
    @song = Song.find(params[:id])
  end

  def update
    @song = Song.find(params[:id])

    @song.artist_ids = params[:@song][:artist_ids]
    @song.album_ids = params[:@song][:album_ids]
    @song.genre_ids = params[:@song][:genre_ids]

    if @song.update_attributes(params[:song])
      redirect_to songs_path
    else
      render :edit
    end  
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/albums/_form.html.erb
<%= form_for(@album, :html => {:multipart => true}) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class ="csslabel">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  

  <% Song.all.each do |song| %>
    <span><%= song.name %></span>
    <%= check_box_tag '@album[song_ids][]', song.id, @album.songs.include?(song) %>
  <% end %>
  
  </div>

  <div class="field">
    
  	<label>Album Photo</label>
    
    <%= f.file_field :photo %> 
    <%= f.hidden_field :photo_cache %>
    <div class ="csslabel">
    <%= f.text_field :remote_photo_url %>
    <%= image_tag(@album.photo_url) if @album.photo? %> 
    </div>




      <%= f.submit %>
  
  </div>

  
  
  
<% end %>

app/views/albums/edit.html.erb
<div id="container">
	<div id="albums" class="generic-box">		

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albums_path %>



	</div>
</div><!-- #container --> 

app/views/albums/index.html.erb
<div id="container">
	<div id="albums" class="generic-box">		
    <ul id = "artist_list">
    	<% @albums.each do |album| %>
      	<li><%= link_to image_tag(album.photo), album_path(album) %></li>
    	<% end %>
    </ul>
    <div class="library_subtitle">
      <%= link_to "+ Add New Album", new_album_path %>
    </div><!-- .library_subtitle -->
	</div><!-- .generic-box -->
</div><!-- #container --> 

app/views/albums/new.html.erb
<div id="container">
	<div id="albums" class="generic-box">		

<%= render 'form' %>

<%= link_to 'Back', albums_path %>


	</div>
</div><!-- #container --> 

app/views/albums/show.html.erb
<div id="album_styles">
	<div id="albums" class="generic-box">		

    <div class = "album_item_container clearfix"> 
      <div class = "album_album_photo"><%= image_tag @album.photo.thumb.url %></div><!-- .album_album_photo -->
      <div class = "album_side_info">
        <div class = "album_title"><%= @album.name %></div><!-- .album_title -->

        <div><span class="infomatics"><%= link_to "Edit Album", edit_album_path(@album) %> | <%= link_to "Delete Album", album_path(@album), :method => :delete, :confirm => "Are you sure?" %> </span></div>
      </div><!-- .album_album_info -->

    </div><!-- .album_info_container -->

	</div><!-- #albums -->
</div><!-- #container --> 

app/views/artists/_form.html.erb
<%= form_for @artist do |f| %>

  <% if @artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@artist.errors.count, "error") %> prohibited this artist info from being saved:</h2>

      <ul>
      <% @artist.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class ="csslabel">
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

  <% Song.all.each do |song| %>
    <span><%= song.name %></span>
    <%= check_box_tag '@artist[song_ids][]', song.id, @artist.songs.include?(song) %>
  <% end %>

    	<label>Artist Photo</label>
      <%= f.file_field :photo %> 
      <%= f.hidden_field :photo_cache %>

    <div class="csslabel">
      <%= f.text_field :remote_photo_url %>
      <%= image_tag(@artist.photo_url) if @artist.photo? %> 
    </div>
  
  <%= f.submit %>   
  </div><!-- .field -->
<% end %>

app/views/artists/create.html.erb
<div id="container">
	<div id="artists" class="generic-box">	

<%= render 'form' %>

	</div>
</div>

app/views/artists/edit.html.erb
<div id="container">
	<div id="artists" class="generic-box">	

<%= render 'form' %>

	</div>
</div>

app/views/artists/index.html.erb
<div id="container">
	<div id="artists" class="generic-box">		
    <ul id="artist_list">
      <% @artists.each do |artist| %> 
        <li>
        <%= link_to image_tag(artist.photo), artist_path(artist) %>
        </li>
      <% end %>
    </ul>
    <div class="library_subtitle">
      <%= link_to "+ Add New Artist", new_artist_path %>
    </div><!-- .library_subtitle -->
	</div><!-- .generic-box -->
</div><!-- #container --> 

app/views/artists/new.html.erb
<div id="container">
	<div id="artists" class="generic-box">	

<%= render 'form' %>

	</div>	
</div>

app/views/artists/show.html.erb
<div id="artists_styles">
	<div id="artists" class="generic-box">	
    <div class="update clearfix">

      <div class="artist_name">
        <%= @artist.name %>
        <%= image_tag @artist.photo, :class => "artist_photo_show" %>
      </div><!-- .artist_name -->



      <div class="artist_show_right">  
        <ul>
          <% @artist.songs.map(&:albums).flatten.uniq.each do |album| %>
            <li><%= link_to album.name, album %></li>
          <% end %>
        </ul>

      </div><!-- .artist_show"_right -->
    </div><!-- .update -->

    <div class = "menu_options">
        <%= link_to "Edit Artist Information", edit_artist_path(@artist) %>
        <%= link_to "Delete Artist from Library", artist_path(@artist), :method => :delete, :confirm => "Are you sure?" %>    
    </div><!-- .menu_options -->
	</div><!-- #artists -->
</div><!-- #container -->

app/views/home/index.html.erb
<div id="container">

	<div id="top-box" class="generic-box">

		<h1 class="logo">SONG-A-TRON</h1>
		<nav id="top-art"></nav>

		<div class="whitespacing"></div>
		
	</div>
</div><!-- #container --> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SONG-A-TRON</title>
  <%= stylesheet_link_tag "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>

  <link href='http://fonts.googleapis.com/css?family=Monoton' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Corben' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Offside' rel='stylesheet' type='text/css'>
  
</head>

<body>
  <!-- <div id="top"> -->
  	<nav>
    	<span class='mini-logo clearfix' >SONG-A-TRON</span>
    	<div>
	      <%= link_to "Home", root_path %>
	      <%= link_to "Artists", artists_path %>
	      <%= link_to "Albums", albums_path %>
	      <%= link_to "Songs", songs_path %>
	      <%= link_to "Show Library", libraries_path %>
      </div>
    </nav>
  <!-- </div> -->
    
  
  <!-- <div class="clear"></div>
 -->
  <div id = 'yield-styling'>
  	<%= yield %>
  </div> <!-- #yield-styling -->

  <footer>
    <div class="sprite clearfix" id="social-media">
      <ul>
        <li><a href="#" class="facebook">Facebook</a></li>
        <li><a href="#" class="twitter">Twitter</a></li>
        <li><a href="#" class="linkedin">LinkedIn</a></li>  
      </ul>
    </div><!-- #social-media -->

    <div id="copyright">a SONG-A-TRON production</div>

    <span id="left"> © 2012 Song-a-Tron :: All rights reserved | | | | HandCoded by Zahra Jabini :: Raymond Chan :: Hsi-Chang Lin :: Audric Kim</span>
    
  </footer>

</body>
</html>

app/views/libraries/index.html.erb
<div id="library_styles">
  <div id="library">

    <% @albums.each do |album| %> 
    
      <div class="library_item_container clearfix">
        <div class="library_album_photo">
          <%= link_to image_tag(album.photo), album_path(album) %>
        </div><!-- .library_album_photo -->
        <div class="library_side_info">
          <div class="library_album"><%= link_to album.name, album_path(album) %></div><!-- .library_album -->
          <% if album.songs.any? %>
            <ul class="library_songs">
            <% album.songs.each do |song| %>
              <li><%= link_to song.name, song_path(song) %></li>
            <% end %> 
            </ul>
          <% end %>
          
        </div><!-- .library_side_info -->
      </div><!-- .library_item_container -->
    <% end %>



  </div><!-- #library -->
</div><!-- #library_styles -->

app/views/shared/_youtube.html.erb
<% url = youtube[(youtube.index("v=")+2)..-1] %>
<% if url.include? "&" %>
  <% video = url[0..(url.index("&")-1)] %>
<% else %>
  <% video = url %>
<% end %>
<% final = "http://www.youtube.com/embed/#{video}" %>

<iframe width="480" height="360" src="<%= final %>" frameborder="0" allowfullscreen></iframe>

app/views/songs/_form.html.erb
<%= form_for @song, :html => {:multipart => true} do |f| %>

  <% if @song.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
      <% @song.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class='field'>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class='field'>
    <h3>Albums</h3>
    <% Album.all.each do |album| %>
      <span><%= album.name %></span>
      <%= check_box_tag '@song[album_ids][]', album.id, @song.albums.include?(album) %>
    <% end %>
  </div>

  <div class='field'>
    <h3>Artists</h3>
    <% Artist.all.each do |artist| %>
      <span><%= artist.name %></span>
      <%= check_box_tag '@song[artist_ids][]', artist.id, @song.artists.include?(artist) %>
    <% end %>
  </div>

  <div class='field'>
    <h3>Genres</h3>
    <% Genre.all.each do |genre| %>
      <span><%= genre.name %></span>
      <%= check_box_tag '@song[genre_ids][]', genre.id, @song.genres.include?(genre) %>
    <% end %>
  </div>

  <div class='field'>
    <%= f.label :photo %>
    <%= f.file_field :photo %>
  </div>
  <div class='field'>
    <%= f.label :photo_url %>
    <%= f.text_field :remote_photo_url %>
  </div>
  <div class='field'>
    <%= f.hidden_field :photo_cache %>
    <%= image_tag(@song.photo_url) if @song.photo? %>
  </div>
  <div class="field">
    <%= f.label :audio %>
    <%= f.file_field :audio %>
  </div>
  <div class="field">
    <%= f.label :youtube %>
    <%= f.text_field :youtube %>
  </div>
  <div class='field'>
    <%= f.submit %>
  </div>


<% end %>

app/views/songs/create.html.erb
<div id="container">
	<div id="songs" class="generic-box">	

<%= render 'form' %>

	</div>
</div>

app/views/songs/edit.html.erb
<div id="container">
	<div id="songs" class="generic-box">	
    <%= render 'form' %>
	</div>
</div>

app/views/songs/index.html.erb
<div id="container">
	<div id="songs" class="generic-box">	
    <% @songs.each do |song| %> 
      <div class="song_box">
        <%= link_to image_tag(song.photo), song_path(song) %> <br>
        <%= link_to song.name, song_path(song) %>
      </div><!-- .song_box -->
    <% end %>
		<div class="library_subtitle">
      <%= link_to "+ Add New Song", new_song_path %>
    </div><!-- .library_subtitle -->
	</div>
</div><!-- #container --> 

app/views/songs/new.html.erb
<div id="container">
	<div id="songs" class="generic-box">	
    <%= render 'form' %>
	</div><!-- #songs -->
</div><!-- #container -->

app/views/songs/show.html.erb
<div id="song_styles">
  <div id="song" class="generic-box">   

    <div class = "song_item_container clearfix"> 
      <div class = "song_album_photo"><%= image_tag @song.photo.thumb.url %></div><!-- .song_album_photo -->
      <div class = "song_side_info">
        <div class = "song_title"><span class="infomatics">artist: </span>
          <% @song.artists.each do |artist| %>
            <%= artist.name %>
          <% end %>
          </div><!-- .song_title -->
        <div class = "song_album"><span class="infomatics">track: <%= @song.name %></span></div><!-- .song_album -->

        <div class = "song_album"><span class="infomatics">albums: </span>
          <% @song.albums.each do |album| %>
            <%= album.name %>
          <% end %>
        </div><!-- .song_album -->

        <div class = "song_album"><span class="infomatics">genres: </span>
          <% @song.genres.each do |genre| %>
            <%= genre.name %>
          <% end %>
        </div><!-- .song_album -->

        <!-- MP3 IS SHOWN HERE -->
        <br>
        <div class = "song_album">  <b>MP3:</b>
          <%= audio_tag @song.audio, :controls => true %>
        </div><!-- .song_album -->

        <!-- YOU TUBE VIDEO IS SHOWN HERE -->
        <br>
        <div class = "song_album youtube">
          <%= render :partial => 'shared/youtube', :locals => {:youtube => @song.youtube } %>
        </div><!-- .song_album -->




        <br>
        <div><span class="infomatics"><%= link_to "Edit Song", edit_song_path(@song) %> | <%= link_to "Delete Song", song_path(@song), :method => :delete, :confirm => "Are you sure?" %> </span></div>
      </div><!-- .song_side_info -->
    </div><!-- .song_item_container -->

  </div><!-- #song -->
</div><!-- #container --> 